# Usar una imagen base con JDK 17 y Gradle 8.3
FROM gradle:8.3-jdk17 AS build

# Establecer un directorio de trabajo
WORKDIR /app

# Copiar archivos de tu proyecto al directorio de trabajo
COPY . /app

# Ejecutar Gradle para construir el proyecto
RUN gradle clean build

# Crear una nueva imagen basada en OpenJDK 8
FROM adoptopenjdk:17-jdk-hotspot

# Exponer el puerto que utilizará la aplicación
EXPOSE 8080

# Copiar el JAR construido desde la etapa de construcción
COPY --from=build /app/build/libs/DailyPost-0.0.1-SNAPSHOT.jar /app/DailyPost-0.0.1-SNAPSHOT.jar

EXPOSE 8080

# Establecer el punto de entrada para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "/app/DailyPost-0.0.1-SNAPSHOT.jar"]

