# Build stage
FROM openjdk:17-jdk AS build

WORKDIR /app

# Copiar todo el contenido al directorio de trabajo
COPY . .

# Ejecutar el build con Gradle
RUN ./gradlew build

# Run stage
FROM openjdk:17-jdk AS final

WORKDIR /app

# Copiar el JAR construido desde la etapa de construcción
COPY --from=build /app/build/libs/DailyPost-0.0.1-SNAPSHOT.jar ./app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]

